### PR TITLE
Support Hi-C files in BAM format

### LINKED ISSUE #87: ERROR ~ toIndex = 2 -- Check script 'genomenote/./workflows/genomenote.nf' at line: 98
### Description of the bug

Hi. I'm interested in trying this pipeline, but running into issues. The main one is the error immediately after running:
```{bash}
ERROR ~ toIndex = 2

 -- Check script 'genomenote/./workflows/genomenote.nf' at line: 98 or see '.nextflow.log' file for more details
```
My commands and the sample sheet are below. Thanks!

### Command used and terminal output

```console
DIRIN=/mount/home/user/data/WorkData/proj1/2023-08.HiC_test
INPUT=${DIRIN}/samplesheet_genomenote.csv
DIROUT=${DIRIN}/OUT_genomenote
GENOME=/mount/home/user/data/ExtData/UCSC/hg38/hg38.fa
nextflow run sanger-tol/genomenote --input ${INPUT} \
  --outdir ${DIROUT} \
  --fasta ${GENOME} \
  -profile singularity
```

### Relevant files

sample,datatype,datafile
sample1,hic,/mount/home/user/data/WorkData/proj1/2023-08.HiC_test/sample1/data/aligned/merged_dedup.bam
sample2,hic,/mount/home/user/data/WorkData/proj1/2023-08.HiC_test/sample2/data/aligned/merged_dedup.bam

### System information

Nextflow version 23.04.3 build 5875
HPC
local
singularity
CentOS
latest cloned sanger-tol/genomenote

### PR DESCRIPTION
**Pull request by muffato**
Fixes #87 

In this pull-request I add support for Hi-C files being given as BAM. The pipeline will then skip the conversion CRAM→BAM.

Test with this samplesheet
```
sample,datatype,datafile
uoEpiScrs1,pacbio,https://tolit.cog.sanger.ac.uk/test-data/Epithemia_sp._CRS-2021b/genomic_data/uoEpiScrs1/pacbio/m64228e_220617_134154.ccs.bc1015_BAK8B_OA--bc1015_BAK8B_OA.rmdup.subset.bam
uoEpiScrs1,pacbio,https://tolit.cog.sanger.ac.uk/test-data/Epithemia_sp._CRS-2021b/genomic_data/uoEpiScrs1/pacbio/m64016e_220621_193126.ccs.bc1008_BAK8A_OA--bc1008_BAK8A_OA.rmdup.subset.bam
uoEpiScrs1,hic,https://tolit.cog.sanger.ac.uk/test-data/Epithemia_sp._CRS-2021b/analysis/uoEpiScrs1.1/read_mapping/hic/GCA_946965045.1.unmasked.hic.uoEpiScrs1.subsampled.bam
```

I'm not changing the test profile yet because:

1. the pipeline can't generate two contact maps
2. when using BAM, a step is _skipped_, so using CRAM ensures higher test coverage.

This may change in #103

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/genomenote/tree/master/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by priyanka-surana** [comment]
A single HiC sample is used to generate genome, so why would we want to generate two HiC maps for separate samples. I do not understand the biological use case.

**Comment by muffato** [comment]
> A single HiC sample is used to generate genome, so why would we want to generate two HiC maps for separate samples. I do not understand the biological use case.

I think this comment should go to #103 ?

**Review by priyanka-surana — APPROVED** [review]
Looks good to me. I am running the tests now.

**Comment by priyanka-surana** [comment]
> Looks good to me. I am running the tests now.

Small suggestion: Can you please add a test to check this modification? Thanks.

**Comment by muffato** [comment]
Just added the Crumble citation. I had missed it !

**Pull request merged**
