### PR TITLE
Genome metadata

### LINKED ISSUE #71: Genome metadata
### Description of feature

Improve genome metadata fetching and processing

### PR DESCRIPTION
**Pull request by BethYates**
Added new module as part of the genome_metadata.nf sub workflow to parse an ENA assembly report XML file and output required parameter-value pairs to a csv file. A module still to be written will combine these paramter-values with those from other sources to provide a comprehensive genome meta-data set

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/genomenote/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/genomenote _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by priyanka-surana — CHANGES_REQUESTED** [review]
1. Can you add `version` statements in both the subworkflow and `workflow/test.nf`?
2. What command do you use for testing?

**Comment by BethYates** [comment]
> 1. Can you add `version` statements in both the subworkflow and `workflow/test.nf`?
> 2. What command do you use for testing?

Version statements have been added. To test I use " nextflow run . -profile sanger,test,singularity"

**Comment by priyanka-surana** [comment]
How are you using `test` and `sanger` together? The reason I am asking is because `test` overrides the max `sanger` resources by default.

**Review by priyanka-surana — APPROVED** [review]
LGTM for now 👍🏼 We have discussed changes once the merge from #63 is done.

**Pull request merged**
