### PR TITLE
Ci compute update

### PR DESCRIPTION
**Pull request by gq1**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/genomenote/tree/master/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by gq1** [comment]
https://cloud.seqera.io/orgs/sanger-tol/workspaces/github-ci/watch/5VUhThWsZpmaJm 
The job completed successfully now.

**Comment by muffato** [comment]
Oki, thanks. In that case, to avoid the risk of other pipelines failing for the same reason. Should we apply the plan you discussed last time ? i.e. change the `TOWER_COMPUTE_ENV` value to point at the 4 GB environment.
That way, all pipelines are changed at once.

From the perspective of compute efficiency, I'd be OK with that because it is justified and limited (there aren't that many Tower jobs coming through)

**Comment by gq1** [comment]
> Oki, thanks. In that case, to avoid the risk of other pipelines failing for the same reason. Should we apply the plan you discussed last time ? i.e. change the `TOWER_COMPUTE_ENV` value to point at the 4 GB environment. That way, all pipelines are changed at once.

Yes, can you update? And then we can close this PR and delete the new repo level secret I added this morning.

**Comment by muffato** [comment]
Changed.
At the same time I've renamed the environments in Tower to be explicit about the RAM (rather than "small", "large")

**Comment by gq1** [comment]
Repo level secret deleted and no action for this PR itself.

**Pull request closed without merging**
